### ISSUE TITLE
Windows paths not working?

### ISSUE THREAD

**Issue by ForsakenHarmony** [anthraxx/intellij-awesome-console#21]
```txt
> feathers-test@0.0.0 watch C:\{...}
> rollup -c --watch

checking rollup-watch version...
bundling...

C:\Users\{...}\src\client\app\ui\router.jsx
  1:8  error  'Router' is defined but never used  no-unused-vars
  2:8  error  'Index' is defined but never used   no-unused-vars
  3:8  error  'Signup' is defined but never used  no-unused-vars
  4:8  error  'Login' is defined but never used   no-unused-vars

✖ 4 problems (4 errors, 0 warnings)

Use of `eval` (in C:\{...}\node_modules\rubberduck\lib\rubberduck.js) is strongly discouraged, as it poses security risks and may cause issues with minification. See https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval for more details
Use of `eval` (in C:\{...}\node_modules\rubberduck\lib\rubberduck.js) is strongly discouraged, as it poses security risks and may cause issues with minification. See https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval for more details
TODO
Error: TODO
    at callHasEffects (C:\{...}\node_modules\rollup\src\ast\nodes\shared\callHasEffects.js:60:11)
    at Node.hasEffects (C:\{...}\node_modules\rollup\src\ast\nodes\CallExpression.js:29:10)
    at Node.hasEffects (C:\{...}\node_modules\rollup\src\ast\Node.js:58:32)
    at fnHasEffects (C:\{...}\node_modules\rollup\src\ast\nodes\shared\callHasEffects.js:17:13)
    at callHasEffects (C:\{...}\node_modules\rollup\src\ast\nodes\shared\callHasEffects.js:34:9)
    at Node.hasEffects (C:\{...}\node_modules\rollup\src\ast\nodes\CallExpression.js:29:10)
    at Node.isUsedByBundle (C:\{...}\node_modules\rollup\src\ast\nodes\CallExpression.js:40:15)
    at C:\{...}\node_modules\rollup\src\Bundle.js:162:31
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki

Process finished with exit code 0
```

I put the `{...}` it's just the path of the project but nothing in here is clickable

**Comment by ForsakenHarmony** [comment]
nvm there's already #16

**Comment by anthraxx** [comment]
@ForsakenHarmony actually it should be fixed in the current git HEAD, we will upload a new version very soon
