### ISSUE TITLE
Java class version error

### ISSUE THREAD

**Issue by wallaby-pouch** [anthraxx/intellij-awesome-console#3]
Hi,
I'm the author of the BashSupport plugin and received this error report today. It's related to your plugin, I think...

IDEA build: PS-139.732

awesome/console/AwesomeLinkFilterProvider : Unsupported major.minor version 51.0 [Plugin: awesome.console]
com.intellij.openapi.extensions.impl.PicoPluginExtensionInitializationException: awesome/console/AwesomeLinkFilterProvider : Unsupported major.minor version 51.0 [Plugin: awesome.console]
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:99)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getExtension(ExtensionComponentAdapter.java:122)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:246)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:195)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:110)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:96)
	at com.intellij.execution.impl.ConsoleViewImpl.<init>(ConsoleViewImpl.java:292)
	at com.intellij.execution.impl.ConsoleViewImpl.<init>(ConsoleViewImpl.java:268)
	at com.intellij.execution.console.LanguageConsoleViewImpl.<init>(LanguageConsoleViewImpl.java:44)
	at com.intellij.execution.console.LanguageConsoleViewImpl.<init>(LanguageConsoleViewImpl.java:40)
	at com.intellij.execution.console.LanguageConsoleViewImpl.<init>(LanguageConsoleViewImpl.java:36)
	at com.ansorgit.plugins.bash.runner.repl.BashConsoleRunner.createConsoleView(BashConsoleRunner.java:48)
	at com.ansorgit.plugins.bash.runner.repl.BashConsoleRunner.createConsoleView(BashConsoleRunner.java:41)
	at com.intellij.execution.runners.AbstractConsoleRunnerWithHistory.a(AbstractConsoleRunnerWithHistory.java:86)
	at com.intellij.execution.runners.AbstractConsoleRunnerWithHistory.access$000(AbstractConsoleRunnerWithHistory.java:50)
	at com.intellij.execution.runners.AbstractConsoleRunnerWithHistory$1.run(AbstractConsoleRunnerWithHistory.java:79)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2108)
	at com.intellij.execution.runners.AbstractConsoleRunnerWithHistory.initAndRun(AbstractConsoleRunnerWithHistory.java:76)
	at com.ansorgit.plugins.bash.actions.AddReplAction.actionPerformed(AddReplAction.java:67)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:164)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:266)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:926)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:236)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2012)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:105)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:512)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
	at java.awt.Component.processMouseEvent(Component.java:6288)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3267)
	at java.awt.Component.processEvent(Component.java:6053)
	at java.awt.Container.processEvent(Container.java:2045)
	at java.awt.Component.dispatchEventImpl(Component.java:4649)
	at java.awt.Container.dispatchEventImpl(Container.java:2103)
	at java.awt.Component.dispatchEvent(Component.java:4475)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4633)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4297)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4227)
	at java.awt.Container.dispatchEventImpl(Container.java:2089)
	at java.awt.Window.dispatchEventImpl(Window.java:2588)
	at java.awt.Component.dispatchEvent(Component.java:4475)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:680)
	at java.awt.EventQueue.access$400(EventQueue.java:96)
	at java.awt.EventQueue$2.run(EventQueue.java:639)
	at java.awt.EventQueue$2.run(EventQueue.java:637)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:108)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:119)
	at java.awt.EventQueue$3.run(EventQueue.java:653)
	at java.awt.EventQueue$3.run(EventQueue.java:651)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:108)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:573)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:275)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:200)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:190)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:185)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:177)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:138)
Caused by: com.intellij.diagnostic.PluginException: awesome/console/AwesomeLinkFilterProvider : Unsupported major.minor version 51.0 [Plugin: awesome.console]
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:130)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.loadClass(ExtensionComponentAdapter.java:159)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentImplementation(ExtensionComponentAdapter.java:64)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:71)
	... 62 more
Caused by: java.lang.UnsupportedClassVersionError: awesome/console/AwesomeLinkFilterProvider : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:489)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:195)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:191)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:167)
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
	... 70 more
Caused by:

com.intellij.diagnostic.PluginException: awesome/console/AwesomeLinkFilterProvider : Unsupported major.minor version 51.0 [Plugin: awesome.console]
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:130)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.loadClass(ExtensionComponentAdapter.java:159)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentImplementation(ExtensionComponentAdapter.java:64)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:71)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getExtension(ExtensionComponentAdapter.java:122)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:246)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:195)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:110)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:96)
	at com.intellij.execution.impl.ConsoleViewImpl.<init>(ConsoleViewImpl.java:292)
	at com.intellij.execution.impl.ConsoleViewImpl.<init>(ConsoleViewImpl.java:268)
	at com.intellij.execution.console.LanguageConsoleViewImpl.<init>(LanguageConsoleViewImpl.java:44)
	at com.intellij.execution.console.LanguageConsoleViewImpl.<init>(LanguageConsoleViewImpl.java:40)
	at com.intellij.execution.console.LanguageConsoleViewImpl.<init>(LanguageConsoleViewImpl.java:36)
	at com.ansorgit.plugins.bash.runner.repl.BashConsoleRunner.createConsoleView(BashConsoleRunner.java:48)
	at com.ansorgit.plugins.bash.runner.repl.BashConsoleRunner.createConsoleView(BashConsoleRunner.java:41)
	at com.intellij.execution.runners.AbstractConsoleRunnerWithHistory.a(AbstractConsoleRunnerWithHistory.java:86)
	at com.intellij.execution.runners.AbstractConsoleRunnerWithHistory.access$000(AbstractConsoleRunnerWithHistory.java:50)
	at com.intellij.execution.runners.AbstractConsoleRunnerWithHistory$1.run(AbstractConsoleRunnerWithHistory.java:79)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2108)
	at com.intellij.execution.runners.AbstractConsoleRunnerWithHistory.initAndRun(AbstractConsoleRunnerWithHistory.java:76)
	at com.ansorgit.plugins.bash.actions.AddReplAction.actionPerformed(AddReplAction.java:67)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:164)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:266)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:926)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:236)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2012)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:105)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:512)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
	at java.awt.Component.processMouseEvent(Component.java:6288)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3267)
	at java.awt.Component.processEvent(Component.java:6053)
	at java.awt.Container.processEvent(Container.java:2045)
	at java.awt.Component.dispatchEventImpl(Component.java:4649)
	at java.awt.Container.dispatchEventImpl(Container.java:2103)
	at java.awt.Component.dispatchEvent(Component.java:4475)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4633)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4297)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4227)
	at java.awt.Container.dispatchEventImpl(Container.java:2089)
	at java.awt.Window.dispatchEventImpl(Window.java:2588)
	at java.awt.Component.dispatchEvent(Component.java:4475)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:680)
	at java.awt.EventQueue.access$400(EventQueue.java:96)
	at java.awt.EventQueue$2.run(EventQueue.java:639)
	at java.awt.EventQueue$2.run(EventQueue.java:637)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:108)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:119)
	at java.awt.EventQueue$3.run(EventQueue.java:653)
	at java.awt.EventQueue$3.run(EventQueue.java:651)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:108)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:573)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:275)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:200)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:190)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:185)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:177)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:138)
Caused by: java.lang.UnsupportedClassVersionError: awesome/console/AwesomeLinkFilterProvider : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:489)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:195)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:191)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:167)
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
	... 70 more

**Comment by anthraxx** [comment]
@wallaby-pouch Seems like you are using Java6 (or below) which is an unsupported version and is not recommended for use anymore.
Is there a reason to stick with java6 (or even below) for running IntelliJ or is there any reason not to run java7 (or above) for the IDE?

We may add a hint to the description that the lowest supported major version is java7 as we are using features which require that.

**Comment by wallaby-pouch** [comment]
As I said, I'm just another plugin author who received this stacktrace.

My own plugin is still compiled against Java 6 because there are quite a few mac users who are still running Java 6, as far as I know.

**Comment by anthraxx** [comment]
Java7 (or newer) is available for all OSX versions since 10.7 (which was released 2009).

I recommend him to upgrade his java-runtime for running the IDE (which can be different from the JRE used to run a project inside the IDE).
