### ISSUE TITLE
Create file cache on background

### ISSUE THREAD

**Issue by krasa** [anthraxx/intellij-awesome-console#5]
I created a huge project and every time I execute something, it blocks EDT for 10 seconds

	at sun.nio.fs.WindowsNativeDispatcher.$$YJP$$FindClose(Native Method)
	at sun.nio.fs.WindowsNativeDispatcher.FindClose(WindowsNativeDispatcher.java)
	at sun.nio.fs.WindowsDirectoryStream.close(WindowsDirectoryStream.java:104)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:215)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:69)
	at java.nio.file.Files.walkFileTree(Files.java:2602)
	at java.nio.file.Files.walkFileTree(Files.java:2635)
	at awesome.console.AwesomeLinkFilter.createFileCache(AwesomeLinkFilter.java:178)
	at awesome.console.AwesomeLinkFilter.<init>(AwesomeLinkFilter.java:36)
	at awesome.console.AwesomeLinkFilterProvider.getDefaultFilters(AwesomeLinkFilterProvider.java:12)
	at com.intellij.execution.impl.ConsoleViewImpl.<init>(ConsoleViewImpl.java:299)
	at com.intellij.execution.impl.ConsoleViewImpl.<init>(ConsoleViewImpl.java:266)
	at com.intellij.execution.filters.TextConsoleBuilderImpl.createConsole(TextConsoleBuilderImpl.java:57)
	at com.intellij.execution.filters.TextConsoleBuilderImpl.getConsole(TextConsoleBuilderImpl.java:49)
	at com.intellij.execution.configurations.CommandLineState.createConsole(CommandLineState.java:91)
	at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:81)
	at org.jetbrains.idea.maven.execution.MavenRunConfiguration$1.execute(MavenRunConfiguration.java:83)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.doExecute(DefaultJavaProgramRunner.java:81)
	at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
	at com.intellij.execution.RunProfileStarter.execute(RunProfileStarter.java:39)
	at com.intellij.execution.impl.ExecutionManagerImpl$2.run(ExecutionManagerImpl.java:203)
	at com.intellij.execution.impl.ExecutionManagerImpl.compileAndRun(ExecutionManagerImpl.java:131)
	at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.java:243)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:40)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:64)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:31)
	at org.jetbrains.idea.maven.execution.MavenRunConfigurationType.runConfiguration(MavenRunConfigurationType.java:198)
	at org.jetbrains.idea.maven.execution.MavenRunConfigurationType.runConfiguration(MavenRunConfigurationType.java:182)
	at krasa.mavenrun.action.RunGoalAction.run(RunGoalAction.java:74)
	at krasa.mavenrun.action.RunGoalAction.actionPerformed(RunGoalAction.java:69)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:745)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:741)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:576)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:383)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by krasa** [comment]
never mind, current master works fine.

**Comment by anthraxx** [comment]
@krasa tests are finished and the version including this feature is 7e2974c (`0.1337.5`) which is now also available as regular update.
