### ISSUE TITLE
Exceptions in the fresh EAP

### ISSUE THREAD

**Issue by b1rdex** [anthraxx/intellij-awesome-console#82]
PhpStorm 2021.2 EAP
Build #PS-212.4037.57, built on June 10, 2021
PhpStorm EAP User
Expiration date: July 10, 2021
Runtime version: 11.0.11+9-b1481.1 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 4
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: awesome.console (0.1337.11), com.intellij.properties (212.4037.16), com.wakatime.intellij.plugin (13.0.2), navigate-from-literal (1.8), net.seesharpsoft.intellij.plugins.csv (2.16.4), name.kropp.intellij.makefile (212.4037.9), some.awesome (1.14), NEON support (0.5.1), com.kalessil.phpStorm.phpInspectionsEA (4.0.6.3), de.espend.idea.php.annotation (8.0.0), fr.adrienbrault.idea.symfony2plugin (0.23.209)

An exception is thrown on file path click:
```
java.lang.AbstractMethodError: Receiver class awesome.console.AwesomeLinkFilter$$Lambda$9449/0x00000008000c7440 does not define or inherit an implementation of the resolved method 'abstract void onLinkFollowed(com.intellij.openapi.project.Project, com.intellij.openapi.vfs.VirtualFile, com.intellij.openapi.editor.Editor, com.intellij.openapi.editor.Editor)' of interface com.intellij.execution.filters.HyperlinkInfoFactory$HyperlinkHandler.
	at com.intellij.execution.filters.impl.MultipleFilesHyperlinkInfo.open(MultipleFilesHyperlinkInfo.java:133)
	at com.intellij.execution.filters.impl.MultipleFilesHyperlinkInfo.navigate(MultipleFilesHyperlinkInfo.java:101)
	at com.intellij.execution.filters.HyperlinkInfoBase.navigate(HyperlinkInfoBase.java:28)
	at com.intellij.terminal.JBTerminalWidget.lambda$convertInfo$3(JBTerminalWidget.java:121)
	at com.jediterm.terminal.model.hyperlinks.LinkInfo.navigate(LinkInfo.java:33)
	at com.jediterm.terminal.ui.TerminalPanel$3.mouseClicked(TerminalPanel.java:243)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6655)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4556)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:893)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:759)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:438)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:793)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:489)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by anthraxx** [comment]
Fixed in 0.1337.12 57ebbd699a4576c58b3ca3f0dedaaaeccdf0b43e
