### ISSUE TITLE
"AbstractMethodError" from AwesomeLinkFilter

### ISSUE THREAD

**Issue by voku** [anthraxx/intellij-awesome-console#83]
Hi, in the IDE I only see an "unknown plugin" error, so I am not 100% sure if the problem comes from this plugin?

```
java.lang.AbstractMethodError: Receiver class awesome.console.AwesomeLinkFilter$$Lambda$6694/0x0000000802bfa440 does not define or inherit an implementation of the resolved method 'abstract void onLinkFollowed(com.intellij.openapi.project.Project, com.intellij.openapi.vfs.VirtualFile, com.intellij.openapi.editor.Editor, com.intellij.openapi.editor.Editor)' of interface com.intellij.execution.filters.HyperlinkInfoFactory$HyperlinkHandler.
	at com.intellij.execution.filters.impl.MultipleFilesHyperlinkInfo.open(MultipleFilesHyperlinkInfo.java:133)
	at com.intellij.execution.filters.impl.MultipleFilesHyperlinkInfo.navigate(MultipleFilesHyperlinkInfo.java:101)
	at com.intellij.execution.filters.HyperlinkInfoBase.navigate(HyperlinkInfoBase.java:28)
	at com.intellij.terminal.JBTerminalWidget.lambda$convertInfo$3(JBTerminalWidget.java:123)
	at com.jediterm.terminal.model.hyperlinks.LinkInfo.navigate(LinkInfo.java:33)
	at com.jediterm.terminal.ui.TerminalPanel$3.mouseClicked(TerminalPanel.java:243)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6655)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4556)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:815)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:752)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

---

PhpStorm 2021.2
Build #PS-212.4746.100, built on July 28, 2021
Licensed to Portable UTF-8 / Lars Moelleken
Subscription is active until March 25, 2022.
For non-commercial open source development only.
Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 4.15.0-153-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 5120M
Cores: 4
Registry: run.processes.with.pty=TRUE, ide.tooltip.initialDelay=885, ide.balloon.shadow.size=0
Non-Bundled Plugins: awesome.console (0.1337.11), com.intellij.ideolog (203.0.27.0), net.seesharpsoft.intellij.plugins.csv (2.17.1), mobi.hsz.idea.gitignore (4.2.0), name.kropp.intellij.makefile (212.4746.52), pronskiy.elephpant (0.1.1), com.github.inxilpro.intellijalpine (v0.4.2), NEON support (0.5.1), com.kalessil.phpStorm.phpInspectionsEA (4.0.6.4), me.artspb.idea.eval.plugin (0.4), lv.midiana.misc.phpstorm-plugins.deep-keys (2021.07.18.002), ru.adelf.idea.dotenv (2021.3.0.212)
Current Desktop: ubuntu:GNOME

**Comment by tconroy** [comment]
Also seeing this error.

**Comment by 0kommanix** [comment]
Same here, happens every now and then.

**Comment by tkolleh** [comment]
This error happens regularly when running commands in Pycharm terminal that output many links. Such as test command resulting in failures with links to code.

```
java.lang.AbstractMethodError: Receiver class awesome.console.AwesomeLinkFilter$$Lambda$8328/0x000000080326e040 does not define or inherit an implementation of the resolved method 'abstract void onLinkFollowed(com.intellij.openapi.project.Project, com.intellij.openapi.vfs.VirtualFile, com.intellij.openapi.editor.Editor, com.intellij.openapi.editor.Editor)' of interface com.intellij.execution.filters.HyperlinkInfoFactory$HyperlinkHandler.
	at com.intellij.execution.filters.impl.MultipleFilesHyperlinkInfo.open(MultipleFilesHyperlinkInfo.java:133)
	at com.intellij.execution.filters.impl.MultipleFilesHyperlinkInfo.navigate(MultipleFilesHyperlinkInfo.java:101)
	at com.intellij.execution.filters.HyperlinkInfoBase.navigate(HyperlinkInfoBase.java:28)
	at com.intellij.terminal.JBTerminalWidget.lambda$convertInfo$3(JBTerminalWidget.java:124)
	at com.jediterm.terminal.model.hyperlinks.LinkInfo.navigate(LinkInfo.java:33)
```

```
PyCharm 2021.2.2 (Professional Edition)
Build #PY-212.5284.44, built on September 14, 2021
Runtime version: 11.0.12+7-b1504.28 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.5
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
```

**Comment by cfecherolle** [comment]
Same here, happens a lot since recent updates of IntelliJ IDEA Ultimate (simple use case: I displayed git status and clicked a file link and the error happened)
```
java.lang.AbstractMethodError: Receiver class awesome.console.AwesomeLinkFilter$$Lambda$8518/0x00000008033da040 does not define or inherit an implementation of the resolved method 'abstract void onLinkFollowed(com.intellij.openapi.project.Project, com.intellij.openapi.vfs.VirtualFile, com.intellij.openapi.editor.Editor, com.intellij.openapi.editor.Editor)' of interface com.intellij.execution.filters.HyperlinkInfoFactory$HyperlinkHandler.
	at com.intellij.execution.filters.impl.MultipleFilesHyperlinkInfo.open(MultipleFilesHyperlinkInfo.java:133)
	at com.intellij.execution.filters.impl.MultipleFilesHyperlinkInfo.navigate(MultipleFilesHyperlinkInfo.java:101)
	at com.intellij.execution.filters.HyperlinkInfoBase.navigate(HyperlinkInfoBase.java:28)
	at com.intellij.terminal.JBTerminalWidget.lambda$convertInfo$3(JBTerminalWidget.java:124)
	at com.jediterm.terminal.model.hyperlinks.LinkInfo.navigate(LinkInfo.java:33)
	at com.jediterm.terminal.ui.TerminalPanel$3.mouseClicked(TerminalPanel.java:243)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6655)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4556)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:814)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
